//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKXIconGen.AvaloniaUI.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PKXIconGen.AvaloniaUI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TooltipBlenderPath {
            get {
                return ResourceManager.GetString("TooltipBlenderPath", resourceCulture);
            }
        }
        
        public static string TooltipOptionalArguments {
            get {
                return ResourceManager.GetString("TooltipOptionalArguments", resourceCulture);
            }
        }
        
        public static string TooltipOutputPath {
            get {
                return ResourceManager.GetString("TooltipOutputPath", resourceCulture);
            }
        }
        
        public static string TooltipIconStyle {
            get {
                return ResourceManager.GetString("TooltipIconStyle", resourceCulture);
            }
        }
        
        public static string TooltipRenderScale {
            get {
                return ResourceManager.GetString("TooltipRenderScale", resourceCulture);
            }
        }
        
        public static string TooltipAssetsPath {
            get {
                return ResourceManager.GetString("TooltipAssetsPath", resourceCulture);
            }
        }
        
        public static string TooltipShinyToggle {
            get {
                return ResourceManager.GetString("TooltipShinyToggle", resourceCulture);
            }
        }
        
        public static string TooltipPokemonName {
            get {
                return ResourceManager.GetString("TooltipPokemonName", resourceCulture);
            }
        }
        
        public static string TooltipOutputName {
            get {
                return ResourceManager.GetString("TooltipOutputName", resourceCulture);
            }
        }
        
        public static string TooltipModelPath {
            get {
                return ResourceManager.GetString("TooltipModelPath", resourceCulture);
            }
        }
        
        public static string TooltipShinyInfo {
            get {
                return ResourceManager.GetString("TooltipShinyInfo", resourceCulture);
            }
        }
        
        public static string TooltipShinyModelPath {
            get {
                return ResourceManager.GetString("TooltipShinyModelPath", resourceCulture);
            }
        }
        
        public static string TooltipBackgroundColor {
            get {
                return ResourceManager.GetString("TooltipBackgroundColor", resourceCulture);
            }
        }
        
        public static string TooltipGlowColor {
            get {
                return ResourceManager.GetString("TooltipGlowColor", resourceCulture);
            }
        }
        
        public static string TooltipInsertAssetsPath {
            get {
                return ResourceManager.GetString("TooltipInsertAssetsPath", resourceCulture);
            }
        }
        
        public static string TooltipBoxToggle {
            get {
                return ResourceManager.GetString("TooltipBoxToggle", resourceCulture);
            }
        }
        
        public static string TooltipBoxAnimationFrame {
            get {
                return ResourceManager.GetString("TooltipBoxAnimationFrame", resourceCulture);
            }
        }
        
        public static string TextureDownloaderInfo {
            get {
                return ResourceManager.GetString("TextureDownloaderInfo", resourceCulture);
            }
        }
        
        public static string TooltipLogBlender {
            get {
                return ResourceManager.GetString("TooltipLogBlender", resourceCulture);
            }
        }
    }
}
