// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKXIconGen.Core.Services;

namespace PKXIconGen.Core.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20211206173735_Add-Settings")]
    partial class AddSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("PKXIconGen.Models.Settings", b =>
                {
                    b.Property<uint>("InternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("BlenderOptionalArgs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BlenderOptionalArgs");

                    b.Property<string>("BlenderPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BlenderPath");

                    b.HasKey("InternalID");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            InternalID = 1u,
                            BlenderOptionalArgs = "",
                            BlenderPath = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
