// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKXIconGen.Core.Services;

#nullable disable

namespace PKXIconGen.Core.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20230829015818_RemoveSettingsRenderTarget-DefaultBoxGlow")]
    partial class RemoveSettingsRenderTargetDefaultBoxGlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("PKXIconGen.Core.Data.PokemonRenderData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("BoxRender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"first\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"second\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"third\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}}}")
                        .HasColumnName("BoxRender")
                        .HasAnnotation("Relational:JsonPropertyName", "box");

                    b.Property<string>("FaceRender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":14,\"y\":-13.5,\"z\":5.5},\"focus\":{\"x\":0,\"y\":0,\"z\":0},\"fov\":40,\"is_ortho\":true,\"ortho_scale\":7.31429,\"light\":{\"type\":0,\"strength\":250,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":5}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1},\"glow\":{\"r\":1,\"g\":1,\"b\":1,\"a\":0}}")
                        .HasColumnName("FaceRender")
                        .HasAnnotation("Relational:JsonPropertyName", "face");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("OutputName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "output_name");

                    b.Property<string>("Shiny")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"color1\":{\"r\":0,\"g\":1,\"b\":2,\"a\":3},\"color2\":{\"r\":127,\"g\":127,\"b\":127,\"a\":127},\"face\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":14,\"y\":-13.5,\"z\":5.5},\"focus\":{\"x\":0,\"y\":0,\"z\":0},\"fov\":40,\"is_ortho\":true,\"ortho_scale\":7.31429,\"light\":{\"type\":0,\"strength\":250,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":5}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1},\"glow\":{\"r\":1,\"g\":1,\"b\":1,\"a\":0}},\"box\":{\"first\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"second\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"third\":{\"animation_pose\":0,\"animation_frame\":0,\"main_camera\":{\"pos\":{\"x\":31.51,\"y\":-37.49,\"z\":33.89},\"focus\":{\"x\":0,\"y\":-1.75,\"z\":6.8},\"fov\":36,\"is_ortho\":true,\"ortho_scale\":36.86,\"light\":{\"type\":3,\"strength\":650,\"color\":{\"r\":1,\"g\":1,\"b\":1,\"a\":1},\"distance\":13}},\"removed_objects\":[],\"textures\":[],\"shading\":0,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}}}}")
                        .HasColumnName("Shiny")
                        .HasAnnotation("Relational:JsonPropertyName", "shiny");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IDX_ID")
                        .IsUnique();

                    b.ToTable("PokemonRenderData");
                });

            modelBuilder.Entity("PKXIconGen.Core.Data.Settings", b =>
                {
                    b.Property<uint>("InternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("AssetsPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlenderOptionalArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlenderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("CurrentGame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LogBlender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("RenderScale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaturationBoost")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalID");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            InternalID = 1u,
                            AssetsPath = "",
                            BlenderOptionalArguments = "",
                            BlenderPath = "",
                            CurrentGame = (byte)0,
                            LogBlender = false,
                            OutputPath = "",
                            RenderScale = (byte)1,
                            SaturationBoost = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
