// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKXIconGen.Core.Services;

#nullable disable

namespace PKXIconGen.Core.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260417054906_NullableMainCamera")]
    partial class NullableMainCamera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("PKXIconGen.Core.Data.PokemonRenderData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("BoxRender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"first\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"second\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"third\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}}}")
                        .HasColumnName("BoxRender")
                        .HasJsonPropertyName("box");

                    b.Property<string>("FaceRender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1},\"glow\":{\"r\":1,\"g\":1,\"b\":1,\"a\":0}}")
                        .HasColumnName("FaceRender")
                        .HasJsonPropertyName("face");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("OutputName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("output_name");

                    b.Property<string>("Shiny")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"color1\":{\"r\":0,\"g\":1,\"b\":2,\"a\":3},\"color2\":{\"r\":127,\"g\":127,\"b\":127,\"a\":127},\"face\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1},\"glow\":{\"r\":1,\"g\":1,\"b\":1,\"a\":0}},\"box\":{\"first\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"second\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}},\"third\":{\"animation_name\":0,\"animation_frame\":0,\"main_camera\":null,\"removed_objects\":[],\"textures\":[],\"shading\":1,\"bg\":{\"r\":0,\"g\":0,\"b\":0,\"a\":0},\"glow\":{\"r\":0,\"g\":0,\"b\":0,\"a\":1}}}}")
                        .HasColumnName("Shiny")
                        .HasJsonPropertyName("shiny");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IDX_ID")
                        .IsUnique();

                    b.ToTable("PokemonRenderData");
                });

            modelBuilder.Entity("PKXIconGen.Core.Data.Settings", b =>
                {
                    b.Property<uint>("InternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("AssetsPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlenderOptionalArguments")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlenderPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<byte>("CurrentGame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DevTools")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LogBlender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OutputNameForGame")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OutputNameForTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<byte>("RenderScale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaturationBoost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaveDanceGIF")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalID");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            InternalID = 1u,
                            AssetsPath = "",
                            BlenderOptionalArguments = "",
                            BlenderPath = "",
                            CurrentGame = (byte)0,
                            DevTools = false,
                            LogBlender = false,
                            OutputNameForGame = (byte)0,
                            OutputNameForTarget = (byte)1,
                            OutputPath = "",
                            RenderScale = (byte)1,
                            SaturationBoost = true,
                            SaveDanceGIF = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
